/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsConfig = {
    Auth: {
        Cognito: {
            userPoolId: 'eu-central-1_IY0Cb79ED',
            userPoolClientId: '2cu03ms99b40tv98nsh3feiq0j',
            region: 'eu-central-1',
        }
    }
};

export default awsConfig;
